### ISSUE TITLE
[Suggestion] 1.18.2 Forge Support 

### ISSUE THREAD

**Issue by laptoppunk** [Snownee/AutochefsDelight#1]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

n/a

### Modloader version

n/a

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

it would be great to see this mod support prior versions like 1.18.2. personally, id love to be able to include in the pack I'm working on

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
